name: CI

on:
  schedule:
      - cron: '30 3 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: refresh
        run: |
          bash refresh.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
