name: CI

on:
  schedule:
      - cron: '0 20 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: refresh
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install dnsutils -y
          dig --help
          bash refresh.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
