name: CI

on:
  schedule:
      - cron: '0 20 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: refresh
        run: |
          sudo apt update
          sudo apt install dnsutils -y
          echo "================================================="
          dig @doh.beauty sdfsdf.baidu.com +https +timeout=1
          echo "================================================="
          dig @doh.beauty1 sdfsdf.baidu.com +https +timeout=1
          bash refresh.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
