name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: refresh
        run: |
          bash refresh.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
